source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!# 忽略引入库的所有警告
use_frameworks!

target 'ZXSSwiftAPP' do
  pod 'Alamofire' #网络请求
  pod 'SwiftyJSON' #json解析
  pod 'HandyJSON' #json解析
  pod 'Kingfisher' #下载图片
  pod 'IBAnimatable' #xib属性
  pod 'SwiftTheme' #主题
  pod 'RxSwift' #Swift 语言开发的一门函数响应式编程语言
  pod 'RxCocoa' #
  pod 'SQLite.swift' #存储
  pod 'SVProgressHUD' #网络提示
  pod 'MJRefresh' #刷新
  pod 'SGPagingView' #今日头条新闻多页
  pod 'BMPlayer' #播放器
  pod 'FDFullscreenPopGesture' #全屏手势
  pod 'lottie-ios' #矢量动画
  
end
